### ISSUE TITLE
Status code Meaning

### ISSUE THREAD

**Issue by ogbuifymark** [RemitaNet/remita-inline-sample#1]
I cant find list of status code and its meaning. i can see "status code":"00" or "025" etc. 
and i don't know what this means. It will be nice if it is provided so people can know which status to look out for while consuming your api.

**Comment by omoniyi24** [comment]
@ogbuifymark thanks for choosing Remita,
"00" means "Transaction Completed Successfully" while "025" means "Payment Reference Generated".

Other response codes include:

Code   =>	Description
01  	   =>	 Transaction Approved
02  	   =>	Transaction Failed
012    =>		User Aborted Transaction
020     =>	Invalid User Authentication
021     =>	Transaction Pending
022     =>	Invalid Request
023     =>	Service Type or Merchant Does not Exist
029     =>	Invalid Bank Code
030     =>	Insufficient Balance
031     =>	No Funding Account
032     =>	Invalid Date Format
040     =>	Initial Request OK
999     =>	Unknown Error

**Comment by ogbuifymark** [comment]
@omoniyi24 :+1:
